### ISSUE TITLE
Hey i want to use Gavel in conjunction with Dredd.

### ISSUE THREAD

**Issue by thesageinpilani** [apiaryio/gavel-spec#32]
Hi everyone, 
Thanks for an awesome library, i want to use Gavel with Dredd, Dredd only supports validating 2xx responses, i want to skip the validation by dredd and use my own. I want to use Gavel to check the types of the Values in the response body returned vs response Body expected. It will be a great help if you can tell me how to do this! thanks !! 😀

**Comment by honzajavorek** [comment]
You already are using Dredd with Gavel, as Gavel is the way Dredd validates responses :-)

You are probably facing this - http://dredd.org/en/latest/how-it-works.html Does it solve your problem?

**Comment by thesageinpilani** [comment]
yes, thanks, when i write transaction.skip = false, dredd is sending the request, i thought it won't. I am correct in saying that dredd is indeed sending the request for statusCodes other than 2xx? (when we have transaction.skip = false).

**Comment by honzajavorek** [comment]
Yes, that's correct. Dredd's default behavior for Swagger is to request only 2xx, as those are usually to be tested and get valid responses. If someone wants to include other status codes as well, they can unskip them and Dredd will happily perform the requests.

**Comment by thesageinpilani** [comment]
cool, thanks. I have so many keys in the request body object. Not all are returned for every request. But the dredd is failing the validation since some keys are not present in the body object. Can you tell me how to pass the test by only checking the types of the keys that are returned in the response body.

**Comment by honzajavorek** [comment]
How do you specify the bodies in your Swagger document? As examples or as schemes?

**Comment by honzajavorek** [comment]
Closing this in favor of https://github.com/apiaryio/dredd/issues/1032. I believe your original issue is solved now 😄
