### ISSUE TITLE
Rebuild Relic documentation

### ISSUE THREAD

**Issue by artem-zakharchenko** [apiaryio/gavel-spec#57]
Current live Relic documentation of Gavel seems to use v 3, which is far behind the latest published version (`7.0.2`).

**Comment by honzajavorek** [comment]
I'm working on it :trollface: 

<img width="439" alt="image" src="https://user-images.githubusercontent.com/283441/62311524-46eeff80-b48c-11e9-96ec-e1fb972fafae.png">

**Comment by artem-zakharchenko** [comment]
Alas:

```
Relish is closing down.
We are no longer accepting sign-ups for Relish.
```

**Comment by honzajavorek** [comment]
Uh-oh. Okay...

**Comment by honzajavorek** [comment]
Closing in favor of https://github.com/apiaryio/gavel-spec/issues/59
